In [1]:
''' In this doc, we shall properly implement Mikes method. The previous version 
was too elementary and didnt have tractable gradients. This one will be for a regression case. '''

import numpy as np
import pandas as pd


In [2]:
#We shall now defined the number of input variables as well as the number of observations:

m = 4 #No. variables
n = 400 #No. observations


#NOTE, this will be the number of observations for both the "grid" on which we instantiate the MV Gaussian,
#as well as the draw from this prior.

#Now we define the variance and lengthscales:

m_var = 1
m_len = range(10,m) #We shall have different size lengthscales for the different variables to predefine importance (ARD)

In [3]:
#Now create the grid of data:
X = []
for i in range(m):
    X.append(np.random.uniform(1,5,n))

X = np.array(X)
X = np.transpose(X)


In [4]:
np.shape(X)

(400, 4)

In [14]:
#We shall extract a mean and covariance from this data:

mean = np.mean(X,axis=0)
covariance = np.cov(np.transpose(X))


In [15]:
#We can also define a kernel and GP:

np.random.multivariate_normal(mean, covariance)

array([2.73240496, 2.9338599 , 2.53897418, 3.39430649])

In [5]:
#I think what I've done so far isn't quite correct, I'm looking for a mean function and covariance function

L = np.identity(m)
L[1,1] = 2
L[2,2] = 5
L[3,3] = 10
#for i in range(m):
    #L[i,i] = (i+1)**2
    

def compute_cov(x,y,var,l_matrix):  #x and y are each full observations (vectors)
    d = 0
    m = len(x)
    diff = x-y
    L = np.linalg.inv(l_matrix)
    exponent = -0.5*(np.matmul(np.transpose(diff),np.matmul(L,diff)))
    val = var*np.exp(exponent)
    return val
#This function takes in two observations and outputs a scalar



K = np.empty([n,n])

#Now lets start filling this matrix:



for i in range(n):
    for j in range(n):
        K[i,j] = compute_cov(X[i,:],X[j,:],m_var,L)

K



array([[1.        , 0.19467006, 0.11363344, ..., 0.48822659, 0.25262759,
        0.11278192],
       [0.19467006, 1.        , 0.25082081, ..., 0.55516175, 0.09821265,
        0.02644392],
       [0.11363344, 0.25082081, 1.        , ..., 0.1421401 , 0.01301884,
        0.0316884 ],
       ...,
       [0.48822659, 0.55516175, 0.1421401 , ..., 1.        , 0.09502147,
        0.01485315],
       [0.25262759, 0.09821265, 0.01301884, ..., 0.09502147, 1.        ,
        0.31323082],
       [0.11278192, 0.02644392, 0.0316884 , ..., 0.01485315, 0.31323082,
        1.        ]])

In [6]:
#We can now define our prior GP with 0 mean function and covariance function K
#We can draw a sample from this:

mean = np.zeros((n,1))
mean = mean.reshape(n)

sample = np.random.multivariate_normal(mean, K)
sample

array([ 5.02277962e-01, -1.19696647e-02,  3.13660777e-01, -3.74145068e-01,
        1.15162136e+00, -3.89407910e-01, -1.88725614e-02, -3.18743164e-01,
       -1.16701292e+00, -1.40999310e-01,  5.91855774e-01,  1.33720991e+00,
        5.20136839e-01, -3.78835723e-01,  1.12597671e+00,  9.01354468e-01,
        3.94932931e-01, -1.17650279e-01, -5.21344484e-01, -1.04583817e+00,
       -4.98465143e-02,  1.12675388e+00, -6.07268493e-01,  7.84382695e-01,
        6.03572116e-01,  3.27496957e-01,  2.33698454e-01, -7.52181772e-01,
       -1.18870818e-01,  2.24083614e+00,  8.11257095e-01, -2.94079167e-01,
       -1.23069344e+00, -3.54316288e-01,  1.09354383e-01, -2.66330410e-01,
        1.26110457e+00,  7.22901826e-01, -4.95043378e-01, -7.40028883e-02,
        2.05283436e-01,  5.87694723e-02,  8.13926521e-01,  1.07717143e+00,
        5.14382299e-01, -7.26491442e-01,  1.22682280e-01, -5.68221652e-01,
       -4.03553268e-02,  8.11857608e-02, -3.33055369e-01, -6.59817732e-01,
        2.47347818e-01,  

In [7]:
data = pd.DataFrame(X)
data['Output'] = sample
data

0         1         2         3    Output
0    2.937828  2.146718  1.402961  2.618168  0.502278
1    4.121296  2.447643  4.396986  2.033471 -0.011970
2    3.940303  4.387353  3.075637  4.275894  0.313661
3    4.071174  3.300124  3.449231  1.474823 -0.374145
4    1.358594  2.397611  1.082828  2.004212  1.151621
..        ...       ...       ...       ...       ...
395  3.116573  1.119254  4.407275  3.811609 -1.098280
396  3.129789  2.885687  4.930516  4.125106  0.188284
397  3.990160  2.030863  2.159779  1.185397  0.284345
398  2.078427  1.519454  4.299100  1.439813  0.745573
399  1.577679  2.992995  4.380362  4.576530  0.529574

[400 rows x 5 columns]

In [8]:
data.to_csv("generated_data2.csv",index=False)

In [9]:
data.to_csv("C:/Users/jacob/Documents/4YP data/DataSynthesis/Regression/4x400/data.csv",index=False)