In [2]:
''' In this doc we shall generate our own binary classifier '''
import numpy as np
import pandas as pd

In [43]:
#Begin with ouput = 0
m = 4 #no. variables
n = 100  #no. observations

data_matrix0 = np.zeros(shape=(n,m))
data_matrix0[:,0] = np.random.uniform(0.0,0.5,n)
data_matrix0[:,1] = np.random.uniform(0.0,0.5,n) + np.random.normal(0.0,0.2,n)
data_matrix0[:,2] = np.random.uniform(0.0,0.5,n) + np.random.normal(0.0,0.5,n)
data_matrix0[:,3] = np.random.uniform(0.0,1.0,n)
data_matrix0 = np.c_[data_matrix0, np.zeros(n)]  

In [44]:
data_matrix1 = np.zeros(shape=(n,m))
data_matrix1[:,0] = np.random.uniform(0.5,1.0,n)
data_matrix1[:,1] = np.random.uniform(0.5,1.0,n) + np.random.normal(0.0,0.2,n)
data_matrix1[:,2] = np.random.uniform(0.5,1.0,n) + np.random.normal(0.0,0.5,n)
data_matrix1[:,3] = np.random.uniform(0.0,1.0,n)
data_matrix1 = np.c_[data_matrix1, np.ones(n)]

In [45]:
data_matrix = np.concatenate((data_matrix0, data_matrix1), axis=0)

In [46]:
data_matrix

array([[ 4.18286815e-01,  1.06314865e-01,  3.67642348e-01,
         6.09699167e-01,  0.00000000e+00],
       [ 3.53349529e-01,  2.77904455e-01, -3.57988629e-01,
         8.99121911e-01,  0.00000000e+00],
       [ 1.20200442e-01,  3.97124803e-01, -2.33157233e-02,
         7.89936735e-01,  0.00000000e+00],
       [ 3.95666100e-01, -1.63690828e-01,  9.99947559e-01,
         7.34246356e-01,  0.00000000e+00],
       [ 2.30537487e-01,  2.38472821e-01,  1.86635023e-01,
         4.51945115e-02,  0.00000000e+00],
       [ 6.54498286e-02,  2.77109741e-01, -2.20164826e-01,
         1.99376827e-01,  0.00000000e+00],
       [ 6.60584763e-02,  9.09367600e-02,  8.35004669e-01,
         9.34034324e-01,  0.00000000e+00],
       [ 4.98877652e-01,  1.26769654e-01, -9.80520594e-02,
         4.97423051e-01,  0.00000000e+00],
       [ 6.14173530e-02,  1.34665387e-01,  5.35664948e-01,
         1.91306738e-02,  0.00000000e+00],
       [ 2.34425976e-01,  9.14674723e-02, -6.50760228e-01,
         4.41222000e-01

In [47]:
df = pd.DataFrame(data_matrix,columns=['Feature1', 'Feature2', 'Feature3', 'Feature4', 'Output'])
df

Feature1  Feature2  Feature3  Feature4  Output
0    0.418287  0.106315  0.367642  0.609699     0.0
1    0.353350  0.277904 -0.357989  0.899122     0.0
2    0.120200  0.397125 -0.023316  0.789937     0.0
3    0.395666 -0.163691  0.999948  0.734246     0.0
4    0.230537  0.238473  0.186635  0.045195     0.0
..        ...       ...       ...       ...     ...
195  0.914169  0.674960  0.555632  0.291834     1.0
196  0.655939  0.975107  1.756231  0.129330     1.0
197  0.580440  0.836028  1.212407  0.754453     1.0
198  0.598224  0.628724  1.067184  0.440769     1.0
199  0.950346  0.515356  1.141771  0.026942     1.0

[200 rows x 5 columns]

In [48]:
df.to_csv("ControlData1.csv",index = False)

In [55]:
''' We shall now address the method that Mike suggested: '''


import GPy
import numpy as np
import matplotlib.pyplot as plt

sample_size = 20
input_variables  = 6



x1 = np.linspace(-10,10,sample_size)
x2 = np.linspace(-10,10,sample_size)
x3 = np.linspace(-10,10,sample_size)
x4 = np.linspace(-10,10,sample_size)
x5 = np.linspace(-10,10,sample_size)
x6 = np.linspace(-10,10,sample_size)


aa,bb,cc,dd,ee,ff = np.meshgrid(x1,x2,x3,x4,x5,x6)
coords=np.array((aa.ravel(), bb.ravel(), cc.ravel(), dd.ravel(), ee.ravel(), ff.ravel())).T

plt.scatter(aa.ravel(),ff.ravel())


KeyboardInterrupt: 

In [58]:
n, p = 1, .5
s = np.random.binomial(n, p, sample_size)

Y = np.array(s).T
Y


array([0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [63]:
Y = Y.reshape((20,1))

In [29]:
np.shape(coords)

(46656, 6)

In [30]:
m_var = 1
m_len = 1
kernel = GPy.kern.RBF(input_dim=input_variables, variance=m_var, lengthscale=m_len)
m_gpy = GPy.models.GPClassification(coords,Y,kernel)


AssertionError: 

In [ ]:
kernel = GPy.kern.RBF(input_dim=1, variance=1., lengthscale=1.)
model = GPy.models.GPRegression(X,Y,kernel, noise_var=1e-10)

testX = np.linspace(0, 1, 100).reshape(-1, 1)
posteriorTestY = model.posterior_samples_f(testX, full_cov=True, size=3)
simY, simMse = model.predict(testX)

plt.plot(testX, posteriorTestY)
plt.plot(X, Y, 'ok', markersize=10)
plt.plot(testX, simY - 3 * simMse ** 0.5, '--g')
plt.plot(testX, simY + 3 * simMse ** 0.5, '--g')

In [44]:
a=np.linspace(-2, 2, 5)
b=np.linspace(-2, 2, 5)
c,d=np.meshgrid(a,b)
c+d

array([[-4., -3., -2., -1.,  0.],
       [-3., -2., -1.,  0.,  1.],
       [-2., -1.,  0.,  1.,  2.],
       [-1.,  0.,  1.,  2.,  3.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [57]:
sample_size = 20
input_variables  = 6

X = [np.random.uniform(1,10,sample_size), 
             np.random.uniform(1,10,sample_size),
             np.random.uniform(1,10,sample_size),
             np.random.uniform(1,10,sample_size),
             np.random.uniform(1,10,sample_size),
             np.random.uniform(1,10,sample_size)]
X = np.array(X).T
np.shape(X)

(20, 6)

In [54]:
np.random.uniform(1,10,sample_size)

array([1.50199259, 8.22114232, 6.66906058, 2.6358701 , 4.45298102,
       3.51863474])

In [71]:
m_var = 1
m_len = 1
kernel = GPy.kern.RBF(input_dim=input_variables, variance=m_var, lengthscale=m_len)
m_gpy = GPy.models.GPClassification(X,Y,kernel)

In [72]:
#We now extract a data set from this:

X_test = [np.random.uniform(1,10,sample_size), 
             np.random.uniform(1,10,sample_size),
             np.random.uniform(1,10,sample_size),
             np.random.uniform(1,10,sample_size),
             np.random.uniform(1,10,sample_size),
             np.random.uniform(1,10,sample_size)]
X_test = np.array(X_test).T

posteriorTestY = m_gpy.posterior_samples_f(X_test, full_cov=True, size=1)

In [79]:
posteriorTestY = posteriorTestY.reshape(20,1)
np.shape(posteriorTestY)

(20, 1)

In [80]:
import pandas as pd

df1 = pd.DataFrame(data=X_test)
df2 = pd.DataFrame(data=posteriorTestY)
df2

0
0   1.293914
1   1.338113
2  -0.106200
3   0.684448
4   0.178559
5   1.013347
6  -1.401591
7   0.526745
8  -1.690806
9   0.802039
10 -0.962346
11  1.683249
12 -0.710833
13  0.460161
14  1.491855
15  0.316176
16 -0.038665
17 -0.508659
18 -0.266452
19  0.410088

In [81]:
df1["output"] = df2
df1

0         1         2         3         4         5    output
0   6.151284  9.651607  4.834382  1.325084  3.307177  4.677658  1.293914
1   8.316064  5.259732  4.619325  4.230927  7.734095  1.225778  1.338113
2   3.230798  3.071978  7.070625  8.187365  8.984705  4.289881 -0.106200
3   1.175540  9.039111  5.060018  8.325326  2.581872  6.313984  0.684448
4   5.182673  6.195986  2.367991  2.422671  9.339712  4.493728  0.178559
5   8.999260  9.179302  6.863418  3.537543  1.789332  8.015802  1.013347
6   5.312248  8.307751  8.724600  9.607050  2.040955  1.366650 -1.401591
7   3.612672  3.676541  4.271667  2.269041  8.563461  3.392087  0.526745
8   4.896343  9.233286  8.577509  5.816504  2.770632  9.687817 -1.690806
9   9.078786  7.010217  8.072507  7.941534  7.159484  2.534629  0.802039
10  1.052250  8.681518  5.755001  3.885910  3.154717  6.850567 -0.962346
11  4.623429  1.786099  6.759621  2.633049  5.581938  6.916874  1.683249
12  5.382612  2.659671  1.734711  5.005064  2.142785  7.282388 -0.710833
13  4.035904  8.507890  1.084747  6.019355  2.648638  4.240100  0.460161
14  2.338447  2.154592  7.329864  1.260349  3.908032  3.125375  1.491855
15  1.927925  9.237117  8.034308  3.593125  1.325591  1.694638  0.316176
16  5.001163  9.711501  7.705186  8.753617  6.045815  7.571784 -0.038665
17  6.736159  1.418794  6.234756  8.744153  5.661556  3.465499 -0.508659
18  3.270045  6.290861  8.168430  5.563415  6.837007  9.419702 -0.266452
19  9.788524  3.570257  2.161965  4.110677  6.579601  6.871133  0.410088

In [83]:
df1.to_csv("generated_data.csv",index=False)