In [1]:
''' In this doc, we shall properly implement Mikes method. The previous version 
was too elementary and didnt have tractable gradients. This one will be for a regression case. '''

import numpy as np
import pandas as pd


In [18]:
#We shall now defined the number of input variables as well as the number of observations:

m = 4 #No. variables
n = 200 #No. observations


#NOTE, this will be the number of observations for both the "grid" on which we instantiate the MV Gaussian,
#as well as the draw from this prior.

#Now we define the variance and lengthscales:

m_var = 1
m_len = range(1,m) #We shall have different size lengthscales for the different variables to predefine importance (ARD)

In [19]:
#Now create the grid of data:
X = []
for i in range(m):
    X.append(np.random.uniform(1,10,n))

X = np.array(X)
X = np.transpose(X)


In [20]:
np.shape(X)

(200, 4)

In [71]:
#We shall extract a mean and covariance from this data:

mean = np.mean(X,axis=0)
covariance = np.cov(np.transpose(X))


In [20]:
#We can also define a kernel and GP:

np.random.multivariate_normal(mean, covariance)

array([ 3.7627028 ,  8.09432924,  7.47329929, -0.35269728,  4.66673452,
        4.40494354])

In [21]:
#I think what I've done so far isn't quite correct, I'm looking for a mean function and mean covariance

L = 2*np.identity(m)
#for i in range(m):
    #L[i,i] = (i+1)**2
    

def compute_cov(x,y,var,l_matrix):  #x and y are each full observations (vectors)
    d = 0
    m = len(x)
    diff = x-y
    L = np.linalg.inv(l_matrix)
    exponent = -0.5*(np.matmul(np.transpose(diff),np.matmul(L,diff)))
    val = var*np.exp(exponent)
    return val
#This function takes in two observations and outputs a scalar



K = np.empty([n,n])

#Now lets start filling this matrix:



for i in range(n):
    for j in range(n):
        K[i,j] = compute_cov(X[i,:],X[j,:],m_var,L)

K



array([[1.00000000e+00, 4.31465034e-04, 5.67616493e-19, ...,
        8.31362973e-06, 1.85744588e-06, 2.39356631e-12],
       [4.31465034e-04, 1.00000000e+00, 4.55300384e-12, ...,
        1.94389836e-05, 1.66054170e-02, 4.02208319e-06],
       [5.67616493e-19, 4.55300384e-12, 1.00000000e+00, ...,
        5.53040999e-11, 6.87918959e-08, 5.43763523e-03],
       ...,
       [8.31362973e-06, 1.94389836e-05, 5.53040999e-11, ...,
        1.00000000e+00, 6.23474735e-07, 9.27684875e-09],
       [1.85744588e-06, 1.66054170e-02, 6.87918959e-08, ...,
        6.23474735e-07, 1.00000000e+00, 3.40963456e-05],
       [2.39356631e-12, 4.02208319e-06, 5.43763523e-03, ...,
        9.27684875e-09, 3.40963456e-05, 1.00000000e+00]])

In [22]:
#We can now define our prior GP with 0 mean function and covariance function K
#We can draw a sample from this:

mean = np.zeros((n,1))
mean = mean.reshape(n)

sample = np.random.multivariate_normal(mean, K)
sample

array([ 0.39603085,  1.16841058, -1.10869134, -1.20988981, -0.70921101,
       -2.31847087,  1.50294529,  0.8721    , -0.97029473,  0.23843865,
        0.02045112, -0.11588211, -1.12985686, -1.09838217, -0.6595454 ,
       -1.99111792,  0.43059328,  0.58662334, -1.05229058, -1.49078733,
        0.23100157, -0.05304105,  0.14331402, -0.48221139,  1.20336662,
        0.72653797, -1.41559776, -1.48963149,  1.54329243, -0.49132067,
        0.53605477,  0.21730011,  0.19925233, -0.26907278,  1.31372757,
       -1.17946798,  0.8899017 , -0.22891131,  1.35459221, -1.76696512,
        0.01006718, -0.29689979, -0.41352851, -0.72866219,  2.31386623,
        1.03835958, -0.65978081, -0.57354186, -0.00865825,  0.74162412,
       -0.6479824 , -0.04870051, -0.51054931,  0.43100811,  2.70984553,
       -0.67307293,  1.05994796,  1.59989916, -0.97111802,  0.19021326,
        0.50307046, -0.79681235, -1.23814086,  0.27021967, -0.44850635,
       -0.48014682,  1.43723038, -0.33643808, -0.83123061, -0.63

In [23]:
data = pd.DataFrame(X)
data['Output'] = sample
data

0         1         2         3    Output
0    8.298618  7.990448  2.058391  1.077975  0.396031
1    8.855392  7.037031  6.702554  3.942593  1.168411
2    1.033326  3.936282  6.937451  9.739695 -1.108691
3    4.914224  3.498826  9.307832  6.318492 -1.209890
4    3.659548  6.087176  3.198000  4.393357 -0.709211
..        ...       ...       ...       ...       ...
195  3.321805  4.580834  9.896205  9.068701 -0.605980
196  2.687361  4.545048  3.103580  1.254827 -0.326909
197  8.285668  3.136081  1.797681  5.890192 -1.549318
198  5.448711  5.355949  7.845841  3.134208 -0.671843
199  3.963193  7.356674  7.074983  8.994361  1.051769

[200 rows x 5 columns]

In [24]:
data.to_csv("generated_data2.csv",index=False)

In [17]:
data.to_csv("C:/Users/jacob/Documents/4YP data/DataSynthesis/Regression/4x200/data.csv",index=False)